import { ErrorModalData } from "../errorModalData/errorModalData.interface";
import { GenericObject } from "../generic-object/generic-object.interface";
import { PageHttpStatus } from "../http-status/page-http-status.interface";


// Generated by https://quicktype.io


export interface Field {

}

export interface FeatureValidation extends GenericObject<GenericObject<DataError>> {}

export interface Errors {
    httpStatus: HTTPErrorStatus;
    validations: GenericObject<FeatureValidation>;
}

export interface DataHttpError {
    modal: ErrorModalData;
    page?: PageHttpStatus;
}

export interface DataError {
    data: DataHttpError;
}

export interface HTTPErrorStatus extends GenericObject<DataError> {}


export interface Config {
    apis: Apis;
    errors: Errors;
    languages: Languages;
}

export interface Apis extends GenericObject<Api> {}

export interface Api {
    baseUrl: string;
    apiKey?: string;
    endpoints: Endpoints;
}

export interface Endpoints {
    [key: string]: string;
}

export interface Languages {
    availables: string[];
    default: string;
}


//   export interface Config {
//     endpoints: string[];
//     user_menu: UserMenu[];
//     apiRestJava: string;
//     TOKEN_KEY: string;
//     REFRESH_TOKEN_KEY: string;
//     AUTHORIZATION_HEADER_KEY: string;
//   }
